// Service Worker 注册成功后，浏览器访问的每个请求都会经过 fetch 事件拦截
// Service Worker 注册失败，请求不会进入 fetch 事件
/*
self.addEventListener('fetch', function (event) {
    
    // 打印请求资源网址
    console.info('url is', event.request.url)
    
    event.respondWith(
        // caches 是全局变量，它就是缓存对象
        // 这一步是判断缓存中是否有该资源
        caches.match(event.request).then(function (cacheRes) {
            // cacheRes 不为空，缓存中有该资源，直接返回给浏览器
            // 省去一次 http 请求
            if (cacheRes) {
                return cacheRes;
            }

            // cacheRes 为空，表示缓存中没有该请求
            // 把原始请求拷过来
            var request = event.request.clone(); 

            // fetch 是浏览器自带的请求库，往服务端发送请求
            return fetch(request).then(function (httpRes) {
                // 请求失败了，直接返回失败的结果就好了。。
                if (!httpRes || httpRes.status !== 200) {
                    return httpRes;
                }

                // 请求成功的话，将响应添加到缓存中
                // 下一次请求相同资源时直接从缓存中拿资源，就不用再发请求了
                var responseClone = httpRes.clone();
                caches.open('offline-cache-v1').then(function (cache) {
                    cache.put(event.request, responseClone);
                });

                return httpRes;
            });
        })
    );
})
*/

var cacheName = 'js13kPWA-v1';
var contentToCache = [
    '/docs/Java核心技术36讲/01-开篇词 (1讲)/00丨开篇词丨以面试题为切入点，有效提升你的Java内功.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第01讲丨谈谈你对Java平台的理解？.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第02讲丨Exception和Error有什么区别？.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第03讲丨谈谈final、finally、finalize有什么不同？.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第04讲丨强引用、软引用、弱引用、幻象引用有什么区别？.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第05讲丨String、StringBuffer、StringBuilder有什么区别？.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第06讲丨动态代理是基于什么原理？.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第07讲丨int和Integer有什么区别？.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第08讲丨对比Vector、ArrayList、LinkedList有何区别？.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第09讲丨对比Hashtable、HashMap、TreeMap有什么不同？.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第10讲丨如何保证集合是线程安全的？ConcurrentHashMap如何实现高效地线程安全？.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第11讲丨Java提供了哪些IO方式？NIO如何实现多路复用？.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第12讲丨Java有几种文件拷贝方式？哪一种最高效？.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第13讲丨谈谈接口和抽象类有什么区别？.html',
    '/docs/Java核心技术36讲/02-模块一 Java基础 (14讲)/第14讲丨谈谈你知道的设计模式？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第15讲丨synchronized和ReentrantLock有什么区别呢？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第16讲丨synchronized底层如何实现？什么是锁的升级、降级？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第17讲丨一个线程两次调用start()方法会出现什么情况？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第18讲丨什么情况下Java程序会产生死锁？如何定位、修复？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第19讲丨Java并发包提供了哪些并发工具类？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第20讲丨并发包中的ConcurrentLinkedQueue和LinkedBlockingQueue有什么区别？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第21讲丨Java并发类库提供的线程池有哪几种？分别有什么特点？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第22讲丨AtomicInteger底层实现原理是什么？如何在自己的产品代码中应用CAS操作？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第23讲丨请介绍类加载过程，什么是双亲委派模型？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第24讲丨有哪些方法可以在运行时动态生成一个Java类？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第25讲丨谈谈JVM内存区域的划分，哪些区域可能发生OutOfMemoryError？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第26讲丨如何监控和诊断JVM堆内和堆外内存使用？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第27讲丨Java常见的垃圾收集器有哪些？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第28讲丨谈谈你的GC调优思路？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第29讲丨Java内存模型中的happen-before是什么？.html',
    '/docs/Java核心技术36讲/03-模块二 Java进阶 (16讲)/第30讲丨Java程序运行在Docker等容器环境有哪些新问题？.html',
    '/docs/Java核心技术36讲/04-模块三 Java安全基础 (2讲)/第31讲丨你了解Java应用开发中的注入攻击吗？.html',
    '/docs/Java核心技术36讲/04-模块三 Java安全基础 (2讲)/第32讲丨如何写出安全的Java代码？.html',
    '/docs/Java核心技术36讲/05-模块四 Java性能基础 (3讲)/第33讲丨后台服务出现明显“变慢”，谈谈你的诊断思路？.html',
    '/docs/Java核心技术36讲/05-模块四 Java性能基础 (3讲)/第34讲丨有人说“Lambda能让Java程序慢30倍”，你怎么看？.html',
    '/docs/Java核心技术36讲/05-模块四 Java性能基础 (3讲)/第35讲丨JVM优化Java代码时都做了什么？.html',
    '/docs/Java核心技术36讲/06-模块5 Java应用开发扩展 (4讲)/第36讲丨谈谈MySQL支持的事务隔离级别，以及悲观锁和乐观锁的原理和应用场景？.html',
    '/docs/Java核心技术36讲/06-模块5 Java应用开发扩展 (4讲)/第37讲丨谈谈SpringBean的生命周期和作用域？.html',
    '/docs/Java核心技术36讲/06-模块5 Java应用开发扩展 (4讲)/第38讲丨对比Java标准NIO类库，你知道Netty是如何实现更高性能的吗？.html',
    '/docs/Java核心技术36讲/06-模块5 Java应用开发扩展 (4讲)/第39讲丨谈谈常用的分布式ID的设计方案？Snowflake是否受冬令时切换影响？.html',
    '/docs/Java核心技术36讲/07-周末福利 (2讲)/周末福利丨一份Java工程师必读书单.html',
    '/docs/Java核心技术36讲/07-周末福利 (2讲)/周末福利丨谈谈我对Java学习和面试的看法.html',
    '/docs/Java核心技术36讲/08-结束语 (1讲)/结束语丨技术没有终点.html',
    '/docs/Java核心技术36讲/index.html',
    '/docs/Redis核心技术与实战/01-基本架构：一个键值数据库包含什么？_For_group_share.html',
    '/docs/Redis核心技术与实战/02-数据结构：快速的Redis有哪些慢操作？_For_group_share.html',
    '/docs/Redis核心技术与实战/03-高性能IO模型：为什么单线程Redis能那么快？_For_group_share.html',
    '/docs/Redis核心技术与实战/04-AOF日志：宕机了，Redis如何避免数据丢失？_For_group_share.html',
    '/docs/Redis核心技术与实战/05-内存快照：宕机后，Redis如何实现快速恢复？_For_group_share.html',
    '/docs/Redis核心技术与实战/06-数据同步：主从库如何实现数据一致？_For_group_share.html',
    '/docs/Redis核心技术与实战/07-哨兵机制：主库挂了，如何不间断服务？_For_group_share.html',
    '/docs/Redis核心技术与实战/08-哨兵集群：哨兵挂了，主从库还能切换吗？_For_group_share.html',
    '/docs/Redis核心技术与实战/09-切片集群：数据增多了，是该加内存还是加实例？_For_group_share.html',
    '/docs/Redis核心技术与实战/10-第1～9讲课后思考题答案及常见问题答疑_For_group_share.html',
    '/docs/Redis核心技术与实战/11-“万金油”的String，为什么不好用了？_For_group_share.html',
    '/docs/Redis核心技术与实战/12-有一亿个keys要统计，应该用哪种集合？_For_group_share.html',
    '/docs/Redis核心技术与实战/13-GEO是什么？还可以定义新的数据类型吗？_For_group_share.html',
    '/docs/Redis核心技术与实战/14-如何在Redis中保存时间序列数据？_For_group_share.html',
    '/docs/Redis核心技术与实战/15-消息队列的考验：Redis有哪些解决方案？_For_group_share.html',
    '/docs/Redis核心技术与实战/16-异步机制：如何避免单线程模型的阻塞？_For_group_share.html',
    '/docs/Redis核心技术与实战/17-为什么CPU结构也会影响Redis的性能？_For_group_share.html',
    '/docs/Redis核心技术与实战/18-波动的响应延迟：如何应对变慢的Redis？（上）_For_group_share.html',
    '/docs/Redis核心技术与实战/19-波动的响应延迟：如何应对变慢的Redis？（下）_For_group_share.html',
    '/docs/Redis核心技术与实战/20-删除数据后，为什么内存占用率还是很高？_For_group_share.html',
    '/docs/Redis核心技术与实战/21-缓冲区：一个可能引发“惨案”的地方_For_group_share.html',
    '/docs/Redis核心技术与实战/22-第11～21讲课后思考题答案及常见问题答疑_For_group_share.html',
    '/docs/Redis核心技术与实战/23-旁路缓存：Redis是如何工作的？_For_group_share.html',
    '/docs/Redis核心技术与实战/24-替换策略：缓存满了怎么办？_For_group_share.html',
    '/docs/Redis核心技术与实战/25-缓存异常（上）：如何解决缓存和数据库的数据不一致问题？_For_group_share.html',
    '/docs/Redis核心技术与实战/26-缓存异常（下）：如何解决缓存雪崩、击穿、穿透难题？_For_group_share.html',
    '/docs/Redis核心技术与实战/27-缓存被污染了，该怎么办？_For_group_share.html',
    '/docs/Redis核心技术与实战/28-Pika-如何基于SSD实现大容量Redis？_For_group_share.html',
    '/docs/Redis核心技术与实战/29-无锁的原子操作：Redis如何应对并发访问？_For_group_share.html',
    '/docs/Redis核心技术与实战/30-如何使用Redis实现分布式锁？_For_group_share.html',
    '/docs/Redis核心技术与实战/31-事务机制：Redis能实现ACID属性吗？_For_group_share.html',
    '/docs/Redis核心技术与实战/32-Redis主从同步与故障切换，有哪些坑？_For_group_share.html',
    '/docs/Redis核心技术与实战/33-脑裂：一次奇怪的数据丢失_For_group_share.html',
    '/docs/Redis核心技术与实战/34-第23~33讲课后思考题答案及常见问题答疑_For_group_share.html',
    '/docs/Redis核心技术与实战/35-CodisVSRedisCluster：我该选择哪一个集群方案？_For_group_share.html',
    '/docs/Redis核心技术与实战/36-Redis支撑秒杀场景的关键技术和实践都有哪些？_For_group_share.html',
    '/docs/Redis核心技术与实战/37-数据分布优化：如何应对数据倾斜？_For_group_share.html',
    '/docs/Redis核心技术与实战/38-通信开销：限制RedisCluster规模的关键因素_For_group_share.html',
    '/docs/Redis核心技术与实战/39-Redis6.0的新特性：多线程、客户端缓存与安全_For_group_share.html',
    '/docs/Redis核心技术与实战/40-Redis的下一步：基于NVM内存的实践_For_group_share.html',
    '/docs/Redis核心技术与实战/41-第35～40讲课后思考题答案及常见问题答疑_For_group_share.html',
    '/docs/Redis核心技术与实战/index.html',
    '/docs/Redis核心技术与实战/加餐（一）-经典的Redis学习资料有哪些？_For_group_share.html',
    '/docs/Redis核心技术与实战/加餐（七）-从微博的Redis实践中，我们可以学到哪些经验？_For_group_share.html',
    '/docs/Redis核心技术与实战/加餐（三）-Kaito：我希望成为在压力中成长的人_For_group_share.html',
    '/docs/Redis核心技术与实战/加餐（二）-Kaito：我是如何学习Redis的？_For_group_share.html',
    '/docs/Redis核心技术与实战/加餐（五）-Redis有哪些好用的运维工具？_For_group_share.html',
    '/docs/Redis核心技术与实战/加餐（六）-Redis的使用规范小建议_For_group_share.html',
    '/docs/Redis核心技术与实战/加餐（四）-Redis客户端如何与服务器端交换命令和数据？_For_group_share.html',
    '/docs/Redis核心技术与实战/开篇词-这样学Redis，才能技高一筹_For_group_share.html',
    '/docs/Redis核心技术与实战/期中测试题-一套习题，测出你的掌握程度_For_group_share.html',
    '/docs/Redis核心技术与实战/期中测试题答案-这些问题，你都答对了吗？_For_group_share.html',
    '/docs/Redis核心技术与实战/期末测试-这些Redis核心知识，你都掌握了吗？_For_group_share.html',
    '/docs/Redis核心技术与实战/简介_For_group_share.html',
    '/docs/Redis核心技术与实战/结束语-从学习Redis到向Redis学习_For_group_share.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/00丨开篇词丨洞悉技术的本质，享受科技的乐趣.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/01丨程序员如何用技术变现（上）.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/02丨程序员如何用技术变现（下）.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/03丨Equifax信息泄露始末.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/04丨从Equifax信息泄露看数据安全.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/05丨何为技术领导力？.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/06丨如何才能拥有技术领导力？.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/07丨推荐阅读：每个程序员都该知道的知识.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/08丨Go语言，Docker和新技术.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/09丨答疑解惑：渴望、热情和选择.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/10丨如何成为一个大家愿意追随的Leader？.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/11丨程序中的错误处理：错误返回码和异常捕捉.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/12丨程序中的错误处理：异步编程以及我的最佳实践.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/13丨魔数0x5f3759df.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/14丨推荐阅读：机器学习101.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/15丨时间管理：同扭曲时间的事儿抗争.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/16丨时间管理：如何利用好自己的时间？.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/17丨故障处理最佳实践：应对故障.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/18丨故障处理最佳实践：故障改进.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/19丨答疑解惑：我们应该能够识别的表象和本质.html',
    '/docs/左耳听风/01丨技术基础 (21讲)/20丨Git协同工作流，你该怎么选？.html',
    '/docs/左耳听风/02丨分布式架构 (9讲)/21丨分布式系统架构的冰与火.html',
    '/docs/左耳听风/02丨分布式架构 (9讲)/22丨从亚马逊的实践，谈分布式系统的难点.html',
    '/docs/左耳听风/02丨分布式架构 (9讲)/23丨分布式系统的技术栈.html',
    '/docs/左耳听风/02丨分布式架构 (9讲)/24丨分布式系统关键技术：全栈监控.html',
    '/docs/左耳听风/02丨分布式架构 (9讲)/25丨分布式系统关键技术：服务调度.html',
    '/docs/左耳听风/02丨分布式架构 (9讲)/26丨分布式系统关键技术：流量与数据调度.html',
    '/docs/左耳听风/02丨分布式架构 (9讲)/27丨洞悉PaaS平台的本质.html',
    '/docs/左耳听风/02丨分布式架构 (9讲)/28丨推荐阅读：分布式系统架构经典资料.html',
    '/docs/左耳听风/02丨分布式架构 (9讲)/29丨推荐阅读：分布式数据调度相关论文.html',
    '/docs/左耳听风/03丨编程范式 (11讲)/30丨编程范式游记（1）-起源.html',
    '/docs/左耳听风/03丨编程范式 (11讲)/31丨编程范式游记（2）-泛型编程.html',
    '/docs/左耳听风/03丨编程范式 (11讲)/32丨编程范式游记（3）-类型系统和泛型的本质.html',
    '/docs/左耳听风/03丨编程范式 (11讲)/33丨编程范式游记（4）-函数式编程.html',
    '/docs/左耳听风/03丨编程范式 (11讲)/34丨编程范式游记（5）-修饰器模式.html',
    '/docs/左耳听风/03丨编程范式 (11讲)/35丨编程范式游记（6）-面向对象编程.html',
    '/docs/左耳听风/03丨编程范式 (11讲)/36丨编程范式游记（7）-基于原型的编程范式.html',
    '/docs/左耳听风/03丨编程范式 (11讲)/37丨编程范式游记（8）-Go语言的委托模式.html',
    '/docs/左耳听风/03丨编程范式 (11讲)/38丨编程范式游记（9）-编程的本质.html',
    '/docs/左耳听风/03丨编程范式 (11讲)/39丨编程范式游记（10）-逻辑编程范式.html',
    '/docs/左耳听风/03丨编程范式 (11讲)/40丨编程范式游记（11）-程序世界里的编程范式.html',
    '/docs/左耳听风/04丨弹力设计 (11讲)/41丨弹力设计篇之“认识故障和弹力设计”.html',
    '/docs/左耳听风/04丨弹力设计 (11讲)/42丨弹力设计篇之“隔离设计”.html',
    '/docs/左耳听风/04丨弹力设计 (11讲)/43丨弹力设计篇之“异步通讯设计”.html',
    '/docs/左耳听风/04丨弹力设计 (11讲)/44丨弹力设计篇之“幂等性设计”.html',
    '/docs/左耳听风/04丨弹力设计 (11讲)/45丨弹力设计篇之“服务的状态”.html',
    '/docs/左耳听风/04丨弹力设计 (11讲)/46丨弹力设计篇之“补偿事务”.html',
    '/docs/左耳听风/04丨弹力设计 (11讲)/47丨弹力设计篇之“重试设计”.html',
    '/docs/左耳听风/04丨弹力设计 (11讲)/48丨弹力设计篇之“熔断设计”.html',
    '/docs/左耳听风/04丨弹力设计 (11讲)/49丨弹力设计篇之“限流设计”.html',
    '/docs/左耳听风/04丨弹力设计 (11讲)/50丨弹力设计篇之“降级设计”.html',
    '/docs/左耳听风/04丨弹力设计 (11讲)/51丨弹力设计篇之“弹力设计总结”.html',
    '/docs/左耳听风/05丨管理设计 (6讲)/52丨管理设计篇之“分布式锁”.html',
    '/docs/左耳听风/05丨管理设计 (6讲)/53丨管理设计篇之“配置中心”.html',
    '/docs/左耳听风/05丨管理设计 (6讲)/54丨管理设计篇之“边车模式”.html',
    '/docs/左耳听风/05丨管理设计 (6讲)/55丨管理设计篇之“服务网格”.html',
    '/docs/左耳听风/05丨管理设计 (6讲)/56丨管理设计篇之“网关模式”.html',
    '/docs/左耳听风/05丨管理设计 (6讲)/57丨管理设计篇之“部署升级策略”.html',
    '/docs/左耳听风/06丨性能设计 (5讲)/58丨性能设计篇之“缓存”.html',
    '/docs/左耳听风/06丨性能设计 (5讲)/59丨性能设计篇之“异步处理”.html',
    '/docs/左耳听风/06丨性能设计 (5讲)/60丨性能设计篇之“数据库扩展”.html',
    '/docs/左耳听风/06丨性能设计 (5讲)/61丨性能设计篇之“秒杀”.html',
    '/docs/左耳听风/06丨性能设计 (5讲)/62丨性能设计篇之“边缘计算”.html',
    '/docs/左耳听风/07丨区块链 (6讲)/63丨区块链技术的本质.html',
    '/docs/左耳听风/07丨区块链 (6讲)/64丨区块链技术细节：哈希算法.html',
    '/docs/左耳听风/07丨区块链 (6讲)/65丨区块链技术细节：加密和挖矿.html',
    '/docs/左耳听风/07丨区块链 (6讲)/66丨区块链技术细节：去中心化的共识机制.html',
    '/docs/左耳听风/07丨区块链 (6讲)/67丨区块链技术细节：智能合约.html',
    '/docs/左耳听风/07丨区块链 (6讲)/68丨区块链技术 - 传统金融和虚拟货币.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/69丨程序员练级攻略：开篇词.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/70丨程序员练级攻略：零基础启蒙.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/71丨程序员练级攻略：正式入门.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/72丨程序员练级攻略：程序员修养.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/73丨程序员练级攻略：编程语言.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/74丨程序员练级攻略：理论学科.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/75丨程序员练级攻略：系统知识.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/76丨程序员练级攻略：软件设计.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/77丨程序员练级攻略：Linux系统、内存和网络.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/78丨程序员练级攻略：异步I-O模型和Lock-Free编程.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/79丨程序员练级攻略：Java底层知识.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/80丨程序员练级攻略：数据库.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/81丨程序员练级攻略：分布式架构入门.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/82丨程序员练级攻略：分布式架构经典图书和论文.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/83丨程序员练级攻略：分布式架构工程设计.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/84丨程序员练级攻略：微服务.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/85丨程序员练级攻略：容器化和自动化运维.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/86丨程序员练级攻略：机器学习和人工智能.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/87丨程序员练级攻略：前端基础和底层原理.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/88丨程序员练级攻略：前端性能优化和框架.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/89丨程序员练级攻略：UI-UX设计.html',
    '/docs/左耳听风/08丨程序员练级攻略 (23讲)/90丨程序员练级攻略：技术资源集散地.html',
    '/docs/左耳听风/09丨程序员面试攻略 (4讲)/91丨程序员面试攻略：面试前的准备.html',
    '/docs/左耳听风/09丨程序员面试攻略 (4讲)/92丨程序员面试攻略：面试中的技巧.html',
    '/docs/左耳听风/09丨程序员面试攻略 (4讲)/93丨程序员面试攻略：面试风格.html',
    '/docs/左耳听风/09丨程序员面试攻略 (4讲)/94丨程序员面试攻略：实力才是王中王.html',
    '/docs/左耳听风/10丨高效学习 (5讲)/95丨高效学习：端正学习态度.html',
    '/docs/左耳听风/10丨高效学习 (5讲)/96丨高效学习：源头、原理和知识地图.html',
    '/docs/左耳听风/10丨高效学习 (5讲)/97丨高效学习：深度，归纳和坚持实践.html',
    '/docs/左耳听风/10丨高效学习 (5讲)/98丨高效学习：如何学习和阅读代码.html',
    '/docs/左耳听风/10丨高效学习 (5讲)/99丨高效学习：面对枯燥和量大的知识.html',
    '/docs/左耳听风/11丨高效沟通 (6讲)/100丨高效沟通：Talk和Code同等重要.html',
    '/docs/左耳听风/11丨高效沟通 (6讲)/101丨高效沟通：沟通阻碍和应对方法.html',
    '/docs/左耳听风/11丨高效沟通 (6讲)/102丨高效沟通：沟通方式及技巧.html',
    '/docs/左耳听风/11丨高效沟通 (6讲)/103丨高效沟通：沟通技术.html',
    '/docs/左耳听风/11丨高效沟通 (6讲)/104丨高效沟通：好老板要善于提问.html',
    '/docs/左耳听风/11丨高效沟通 (6讲)/105丨高效沟通：好好说话的艺术.html',
    '/docs/左耳听风/12丨尾声 & 加餐 (2讲)/加餐丨谈谈我的“三观”.html',
    '/docs/左耳听风/12丨尾声 & 加餐 (2讲)/结束语丨业精于勤，行成于思.html',
    '/docs/左耳听风/index.html',
    '/docs/苏杰的产品创新课/00丨开篇词丨人人都是产品经理吗？.html',
    '/docs/苏杰的产品创新课/01丨为什么每个人都要学产品创新课？.html',
    '/docs/苏杰的产品创新课/02丨四轮MVP框架导读：产品从无到有的创新，有通杀的法门吗？.html',
    '/docs/苏杰的产品创新课/03丨从理解用户开始：故事、生态、画像、旅程.html',
    '/docs/苏杰的产品创新课/04丨竞品生态：真正有效的竞品分析怎么做？.html',
    '/docs/苏杰的产品创新课/05丨打造属于你的点子过滤器.html',
    '/docs/苏杰的产品创新课/06丨Y模型：从问题域到方案域的最硬核解题思路.html',
    '/docs/苏杰的产品创新课/07丨用“原型”低成本验证：差个程序员，也可以做产品.html',
    '/docs/苏杰的产品创新课/08丨设计冲刺：谷歌创投如何帮助产品成功？.html',
    '/docs/苏杰的产品创新课/09丨产品服务系统：避免狭隘，再聊什么是产品.html',
    '/docs/苏杰的产品创新课/10丨好产品的评价标准：单一产品的两个维度.html',
    '/docs/苏杰的产品创新课/11丨习惯、启程、发现、精通：一个好产品的起步逻辑.html',
    '/docs/苏杰的产品创新课/12丨和用户一起成长：生命周期，不同阶段怎么运营.html',
    '/docs/苏杰的产品创新课/13丨真正的成功指标：用户数、收入等等都不是.html',
    '/docs/苏杰的产品创新课/14丨赚到钱只是结果：做出来和推出去的效率.html',
    '/docs/苏杰的产品创新课/15丨需求采集：各种方法怎么灵活应用.html',
    '/docs/苏杰的产品创新课/16丨KANO模型：雪中送炭与锦上添花.html',
    '/docs/苏杰的产品创新课/17丨产品进化案例：千岛湖啤酒的脑洞.html',
    '/docs/苏杰的产品创新课/18丨我的实践：这门“产品创新课”本身.html',
    '/docs/苏杰的产品创新课/19丨从产品到产品矩阵：可复用、能积累、善生死.html',
    '/docs/苏杰的产品创新课/20丨组织团队的支撑：面向未来，如何提升你的竞争力.html',
    '/docs/苏杰的产品创新课/index.html',
    '/docs/苏杰的产品创新课/结束语丨死亡是宇宙最伟大的发明.html',
    '/docs/邱岳的产品手记/00丨开篇词丨产品经理的世界没有对错.html',
    '/docs/邱岳的产品手记/01丨验证码是个好设计吗？.html',
    '/docs/邱岳的产品手记/02丨产品经理工具指南.html',
    '/docs/邱岳的产品手记/03丨产品案例分析·Trigraphy的设计哲学.html',
    '/docs/邱岳的产品手记/04丨如何当好AI时代的产品经理？（学习篇）.html',
    '/docs/邱岳的产品手记/05丨如何当好AI时代的产品经理？（实践篇）.html',
    '/docs/邱岳的产品手记/06丨产品案例分析 · The Guardian的文本之美.html',
    '/docs/邱岳的产品手记/07丨关于需求变更（上）：需求背后的需求.html',
    '/docs/邱岳的产品手记/08丨关于需求变更（下）  化变更于无形.html',
    '/docs/邱岳的产品手记/09丨产品案例分析：Hopper的“人工智能”.html',
    '/docs/邱岳的产品手记/10丨产品被抄袭了，怎么办？.html',
    '/docs/邱岳的产品手记/11丨如何借鉴灵感？.html',
    '/docs/邱岳的产品手记/12丨产品案例分析：LabRdr的设计实验.html',
    '/docs/邱岳的产品手记/13丨无用却必要：产品规划（上）.html',
    '/docs/邱岳的产品手记/14丨留白与节奏：产品规划（下）.html',
    '/docs/邱岳的产品手记/15丨产品案例分析：Mimo与Learn Python的导学之趣.html',
    '/docs/邱岳的产品手记/16丨在内部产品中找到产品经理的价值.html',
    '/docs/邱岳的产品手记/17丨产品经理如何获得非权力性的影响力？.html',
    '/docs/邱岳的产品手记/18丨产品案例分析：WWF Together的情怀设计.html',
    '/docs/邱岳的产品手记/19丨产品经理如何与开发打交道（上）：打破思维的边界.html',
    '/docs/邱岳的产品手记/20丨产品经理如何与开发打交道（下）：合作与共赢.html',
    '/docs/邱岳的产品手记/21丨产品案例分析：Fabulous的精致养成.html',
    '/docs/邱岳的产品手记/22丨产品经理的图文基本功（上）：产品文档.html',
    '/docs/邱岳的产品手记/23丨产品经理的图文基本功（下）：产品图例.html',
    '/docs/邱岳的产品手记/24丨产品案例分析：PathSource的混乱与直观.html',
    '/docs/邱岳的产品手记/25丨产品世界的暗黑模式：操纵的诱惑.html',
    '/docs/邱岳的产品手记/26丨写好产品文档的诀窍.html',
    '/docs/邱岳的产品手记/27丨产品案例分析：Quartz&Hooked的对话式交互.html',
    '/docs/邱岳的产品手记/28丨产品分析的套路（上）：谁是利益相关者？.html',
    '/docs/邱岳的产品手记/29丨产品分析的套路（中）：解决什么问题？.html',
    '/docs/邱岳的产品手记/30丨产品案例分析：Primer的扑克牌交互.html',
    '/docs/邱岳的产品手记/31丨产品分析的套路（下）：如何出解决方案？.html',
    '/docs/邱岳的产品手记/32丨从受众规模、需求频率和强度出发：排定需求优先级的方法（上）.html',
    '/docs/邱岳的产品手记/33丨产品案例分析：Arts & Culture 的架构之美.html',
    '/docs/邱岳的产品手记/34丨价值曲线分析：排定需求优先级的方法（下）.html',
    '/docs/邱岳的产品手记/35丨答疑时间：关于产品经理的12个问题.html',
    '/docs/邱岳的产品手记/36丨产品案例分析：解读知识星球.html',
    '/docs/邱岳的产品手记/37丨如何做好需求评审（上）：需求评审不只是一次会议.html',
    '/docs/邱岳的产品手记/38丨如何做好需求评审（下）：在评审中控住全场.html',
    '/docs/邱岳的产品手记/39丨产品案例分析：SeatGeek的订票设计.html',
    '/docs/邱岳的产品手记/40丨新年给产品经理的几碗鸡汤.html',
    '/docs/邱岳的产品手记/41丨产品经理的项目管理心得.html',
    '/docs/邱岳的产品手记/42丨产品案例分析：Unread的阅读体验.html',
    '/docs/邱岳的产品手记/43丨“玩”的力量：从游戏设计中学习产品设计（上）.html',
    '/docs/邱岳的产品手记/44丨“玩”的启示：从游戏设计中学习产品设计（下）.html',
    '/docs/邱岳的产品手记/45丨产品案例分析：Chartistic的“复杂”图表.html',
    '/docs/邱岳的产品手记/index.html',
    '/docs/邱岳的产品手记/【第二季回归】二爷归来，再次扬帆起航.html',
    '/docs/邱岳的产品手记/尾声：你的快乐是哪一种.html'
];

self.addEventListener('install', function(e) {
    console.log('[Service Worker] Install');
    e.waitUntil(
        caches.open(cacheName).then(function(cache) {
            console.log('[Service Worker] Caching all: app shell and content');
            return cache.addAll(contentToCache);
        })
    );
});